# ==============================================================================
# Horizontal Pod Autoscaler (HPA) Configuration
# ==============================================================================
# Automatically scales pods based on CPU/memory usage
# Requires metrics-server to be installed in the cluster
#
# Install metrics-server:
#   kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
#
# Check HPA status:
#   kubectl get hpa -n uex-payments-dev
#   kubectl describe hpa uex-backend-hpa -n uex-payments-dev
# ==============================================================================

---
# HPA for UEX Backend (Critical Service)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: uex-backend-hpa
  namespace: uex-payments-dev
  labels:
    app: uex-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uex-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 4
          periodSeconds: 30
      selectPolicy: Max

---
# HPA for Processing-Tier Backend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: processing-tier-hpa
  namespace: uex-payments-dev
  labels:
    app: processing-tier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: processing-tier
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30

---
# HPA for Management Backend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: management-backend-hpa
  namespace: uex-payments-dev
  labels:
    app: management-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: management-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
# HPA for Client-Tier Frontend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-tier-hpa
  namespace: uex-payments-dev
  labels:
    app: client-tier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-tier
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

---
# HPA for Management-Tier Frontend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: management-tier-hpa
  namespace: uex-payments-dev
  labels:
    app: management-tier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: management-tier
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

---
# HPA for Presentation Dashboard
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: presentation-hpa
  namespace: uex-payments-dev
  labels:
    app: presentation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: presentation
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
